/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author Susi M
 */
public class FormBuku extends javax.swing.JFrame {
public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    
    public final void judul() {
  Object[] judul = {
    "book_id", "title", "authpr", "publicationyear", "publisher","price"
  };
  tabModel = new DefaultTableModel(null, judul);
  tableBuku.setModel(tabModel);
}

public final void tampilData(String where) {
  try {
    Statement statement = koneksi.getConnection().createStatement();
    tabModel.getDataVector().removeAllElements();
    tabModel.fireTableDataChanged();
    ResultSet rs = statement.executeQuery("SELECT * FROM book ");
    
    while (rs.next()) {
      Object[] data = {
        rs.getString("book_id"),
        rs.getString("title"),
        rs.getString("author"),
        rs.getString("publicationyear"),
        rs.getString("publisher"),
        rs.getString("price"),
      };
        
        tabModel.addRow(data);
    }
  } catch(SQLException e) {
  }
}
  public void reset() {
  inputbookid.setText("");
  inputtitle.setText("");
  inputauthor.setText("");
  inputpubyear.setText("");
  inputpublisher.setText("");
  inputprice.setText("");
}  
    
    public FormBuku() {
        initComponents();
        judul();
        tampilData("");
        buttonHapus.setEnabled(true);
        buttonUpdate.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        inputbookid = new javax.swing.JTextField();
        inputtitle = new javax.swing.JTextField();
        inputpubyear = new javax.swing.JTextField();
        inputprice = new javax.swing.JTextField();
        inputpublisher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputauthor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Siswa");

        jLabel2.setText("Book id");

        jLabel3.setText("title");

        jLabel4.setText("publication year");

        jLabel5.setText("publisher");

        jLabel6.setText("price");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBuku);

        inputbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbookidActionPerformed(evt);
            }
        });

        inputtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtitleActionPerformed(evt);
            }
        });

        inputpubyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpubyearActionPerformed(evt);
            }
        });

        inputprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpriceActionPerformed(evt);
            }
        });

        inputpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpublisherActionPerformed(evt);
            }
        });

        jLabel7.setText("author");

        inputauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputauthorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputpubyear))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputprice, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(529, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReset)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inputauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputpubyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonReset))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    try {
     Statement statement;
        statement = koneksi.getConnection().createStatement();
    st.executeUpdate("INSERT INTO book(book_id,title,author,publicationyear,publisher,price) VALUES('" + inputbookid.getText() + "','"
        + inputtitle.getText() + "','"
        + inputauthor.getText() + "','"
        + inputpubyear.getText() + "','"
    + inputpublisher.getText() + "','"
    + inputprice.getText() + "')");
    tampilData("");
    JOptionPane.showMessageDialog(null, "Simpan Berhasil");
    inputbookid.setText("");
    inputtitle.setText("");
    inputauthor.setText("");
    inputpubyear.setText("");
    inputpublisher.setText("");
    inputprice.setText("");
  } catch (HeadlessException | SQLException e) {
  }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
       inputbookid.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 0).toString());
  inputtitle.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 1).toString());
  inputauthor.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 2).toString());
  inputpubyear.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 3).toString());
  inputpublisher.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 4).toString());
  inputprice.setText(tableBuku.getValueAt(tableBuku.getSelectedRow(), 5).toString());
  buttonSimpan.setEnabled(false);
  buttonUpdate.setEnabled(true);
  buttonHapus.setEnabled(true);
    }//GEN-LAST:event_tableBukuMouseClicked

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
         reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
     try {
     Statement statement = koneksi.getConnection().createStatement();
    st.executeUpdate("UPDATE book set " 
        + "title='"      + inputtitle.getText() + "', "
        + "author='"   + inputauthor.getText() + "', "
        + "publicationyear='"  + inputpubyear.getText() + "', "
        + "publisher='"        + inputpublisher.getText() + "', "
        + "price='"    + inputprice.getText() + "' where " + "book_id='"  + inputbookid.getText() + "'" ); 
    tampilData("");
    JOptionPane.showMessageDialog(null, "Update Berhasil");
    reset();
    buttonSimpan.setEnabled(true);
  } catch (HeadlessException | SQLException e) {
  }     
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
          try {
    int jawab;
    
    if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
      Statement statement = koneksi.getConnection().createStatement();
      st.executeUpdate("DELETE FROM book WHERE book_id='"
          + tabModel.getValueAt(tableBuku.getSelectedRow(), 0) + "'");
      tampilData("");
      reset();
       buttonSimpan.setEnabled(true);
    }
  } catch (HeadlessException | SQLException e) {
  }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void inputtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputtitleActionPerformed

    private void inputpubyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpubyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpubyearActionPerformed

    private void inputpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpriceActionPerformed

    private void inputpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpublisherActionPerformed

    private void inputauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputauthorActionPerformed

    private void inputbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputbookidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField inputauthor;
    private javax.swing.JTextField inputbookid;
    private javax.swing.JTextField inputprice;
    private javax.swing.JTextField inputpublisher;
    private javax.swing.JTextField inputpubyear;
    private javax.swing.JTextField inputtitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBuku;
    // End of variables declaration//GEN-END:variables
}
